name : "Protagonist"
person {
   level: "house"
}
save_path: "games/session.pb"

levels {
  key: "house"
  value {
    actions {
      key: "LOOK"
      value {
        description: "You are behind the white house.  In one corner of the house there is a small window which is "
        conditionals {
          clause {
            scope: ITEM
            id: "WINDOW"
            tags: "OPEN"
          }
          left {
            leaf: "open."
          }
          right { 
            leaf: "slightly ajar."
          }
        }
      }
    }
    items {
      key: "WINDOW"
      value {
        state {
          tags: "CLOSE"
        }
        actions {
          key: "OPEN"
          value {
            conditionals {
              clause {
                scope: ITEM
                id: "WINDOW"
                tags: "CLOSE"
              }
              left {
                change {
                  type: REPLACE 
                  context {
                    scope: ITEM
                    id: "WINDOW"
                    tags: "OPEN"
                  }
                  comment: "With great effort, you open the window far enough to allow entry."
                }
              }
            }
          }
        }
        actions {
          key: "CLOSE"
          value {
            conditionals {
              clause {
                scope: ITEM
                id: "WINDOW"
                tags: "OPEN"
              }
              left {
                change {
                  type: REPLACE 
                  context {
                    scope: ITEM
                    id: "WINDOW"
                    tags: "CLOSE"
                  }
                  comment: "The window closes (more easily than it opened)."
                }
              }
            }
          }
        }
      }
    }
  }
}
