levels {
    entrance {
      description : "Where I'm bound to stay Where you sleep all day,Where they hung the jerkThat invented workIn the Big Rock Candy Mountains"
      action {}
    }

    intro : "Welcome to Westworld. "
    npcs {
      name : "NPC: Dolores",
      stats {}
    }
}

name : "Protagonist"

inventory {
  name: "Shovel"
  description : " description: Wooden handle, broad flat blade."
  actions {
    description : "description: Used for moving coal, earth, or snow.",
    name : "dig",
    resultant_level {}
  }
}
