levels {
    entrance {
      description : "Where I'm bound to stay\n Where you sleep all day,\nWhere they hung the jerk\nThat invented work\nIn the Big Rock Candy Mountains\n"
      action {}
    }

    intro : "Welcome to Westworld. \n"
    npcs {
      name : "Dolores",
      stats {}
    }
}
levels {}

name : "Protagonist\n"
inventory {
  name: "Shovel\n"
  description : "description:\n fuck\n"
  actions {
    description : "description:\n You swung the hat\n",
    name : "dig\n",
    resultant_level {}
  }
}
