sudo: true
language: rust
cache: cargo
rust:
  - nightly 

addons:
  apt:
    packages:
      - protobuf-compiler
      - build-essential

install:
  - rustup install nightly

before_script:
  - export PATH=$PATH:~/.cargo/bin
  - cargo install rustfmt --force || true

script:
  - cargo build
  - cargo fmt -- --force --write-mode=diff
  - cargo test
