sudo: true
language: rust
cache: cargo
rust:
  - nightly 

addons:
  apt:
    packages:
      - protobuf-compiler
      - build-essential

install:
  - rustup install nightly
  - rustup component add --toolchain nightly rustfmt-preview

before_script:
  - export PATH=$PATH:~/.cargo/bin
  - cargo install rustfmt || true

script:
  - cargo build
  - cargo +nightly fmt -- --write-mode=diff
  - cargo test
