name: Maeve
version: "0.1"

# All Args must be defined in the 'args:' list where the name of the arg, is the
# key to a Hash object
args:
    - load:
        help: Path to a saved game. 
        short: l
        long: load
        takes_value: true
    - new:
        help: Path to a new game. 
        short: n
        long: new 
        global: true
        takes_value: true
        conflicts_with:
            - load
